### ISSUE TITLE
The client made a bad request: Some items were not indexed.

### ISSUE THREAD

**Issue by bbtimx** [doofinder/doofinder-magento#85]
Hello,
I update the Magento Doofinder Module and after I had to do some product change I always got these error message after saving and Magento don´t save anything.

After comment out line 37 in Utils.php I works.

```
2017-06-01T00:00:00+00:00 ERR (3): 
exception 'Doofinder\Api\Management\Errors\BadRequest' with message 'The client made a bad request: Some items were not indexed. Please check items with ids: [u'50845']' in /var/www/share/htdocs/lib/php-doofinder/src/Management/Errors/Utils.php:37
Stack trace:
#0 /var/www/share/htdocs/lib/php-doofinder/src/Management/Client.php(83): Doofinder\Api\Management\Errors\Utils::handleErrors(400, '{"detail":"Some...')
#1 /var/www/share/htdocs/lib/php-doofinder/src/Management/SearchEngine.php(146): Doofinder\Api\Management\Client->managementApiCall('PUT', '051dc0edf79d025...', NULL, '[{"title":"Klim...')
#2 /var/www/share/htdocs/app/code/community/Doofinder/Feed/Model/Observers/Feed.php(115): Doofinder\Api\Management\SearchEngine->updateItems('product', Array)
#3 /var/www/share/htdocs/app/code/core/Mage/Core/Model/App.php(1358): Doofinder_Feed_Model_Observers_Feed->updateSearchEngineIndexes(Object(Varien_Event_Observer))
#4 /var/www/share/htdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Doofinder_Feed_Model_Observers_Feed), 'updateSearchEng...', Object(Varien_Event_Observer))
#5 /var/www/share/htdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_product...', Array)
#6 /var/www/share/htdocs/app/code/core/Mage/Core/Model/Abstract.php(466): Mage::dispatchEvent('catalog_product...', Array)
#7 /var/www/share/htdocs/app/code/core/Mage/Catalog/Model/Product.php(549): Mage_Core_Model_Abstract->_afterSave()
#8 /var/www/share/htdocs/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Catalog_Model_Product->_afterSave()
#9 /var/www/share/htdocs/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(728): Mage_Core_Model_Abstract->save()
#10 /var/www/share/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->saveAction()
#11 /var/www/share/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#12 /var/www/share/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/share/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/share/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/share/htdocs/index.php(83): Mage::run('', 'store')
#16 {main}
```

Magento Version CE v1.9.3.1

Magento Doofinder v1.8.7

**Comment by carlosescri** [comment]
Hi, we're working on this. Will be fixed in the next release. For the moment you can disable atomic updates through the API in the module's feed configuration. Thanks for reporting this.
